name: Bug Report
description: Report something that's broken
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Help us fix issues in TextDoom.

        **Tip:** Mention `@claude` in comments to request AI assistance with debugging.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug
      placeholder: "When I press spacebar, nothing fires..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What should happen?
      description: Expected behaviour
      placeholder: "The weapon should fire and enemies should take damage"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How do we see this bug?
      placeholder: |
        1. Start single player
        2. Walk up to an enemy
        3. Press spacebar
    validations:
      required: false

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: false
